spring:
  application:
    name: blogger-box-backend
  datasource:
    url: jdbc:postgresql://db.pdxghvvhwgndrftjnilk.supabase.co:5432/postgres
    username: postgres
    password: dauphine1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 1234
